// AUTO-GENERATED. Source: GET /chapters?lang=en and /appendices?lang=en
// Used as a fallback so client-side search matches the English title even when the user reads in another language.
export const CHAPTER_TITLES_EN: Record<number, string> = {
  "1": "The Key",
  "2": "The Heifer",
  "3": "The Amramites",
  "4": "The Women",
  "5": "The Feast",
  "6": "The Livestock",
  "7": "The Purgatory",
  "8": "The Spoils of War",
  "9": "Ultimatum",
  "10": "Jonah",
  "11": "Hood",
  "12": "Joseph",
  "13": "The Thunder",
  "14": "Abraham",
  "15": "The Hijr Valley",
  "16": "The Bee",
  "17": "The Children of Israel",
  "18": "The Cave",
  "19": "Mary",
  "20": "T-H",
  "21": "The Prophets",
  "22": "The Pilgrimage",
  "23": "The Believers",
  "24": "The Light",
  "25": "The Statute Book",
  "26": "The Poets",
  "27": "The Ant",
  "28": "The History",
  "29": "The Spider",
  "30": "The Romans",
  "31": "Luqmaan",
  "32": "Prostration",
  "33": "The Parties",
  "34": "Sheba",
  "35": "Initiator",
  "36": "Y-S",
  "37": "The Arrangers",
  "38": "S",
  "39": "The Throngs",
  "40": "Forgiver",
  "41": "Detailed",
  "42": "Consultation",
  "43": "The Ornaments",
  "44": "The Smoke",
  "45": "The Kneeling",
  "46": "The Dunes",
  "47": "Muhammed",
  "48": "Victory",
  "49": "The Walls",
  "50": "Q",
  "51": "Driver of the Winds",
  "52": "Mount Sinai",
  "53": "The Stars",
  "54": "The Moon",
  "55": "The Gracious",
  "56": "The Inevitable",
  "57": "Iron",
  "58": "The Debate",
  "59": "The Exodus",
  "60": "The Test",
  "61": "The Column",
  "62": "Friday",
  "63": "The Hypocrites",
  "64": "Mutual Blaming",
  "65": "Divorce",
  "66": "Prohibition",
  "67": "Kingship",
  "68": "The Pen",
  "69": "Incontestable",
  "70": "The Heights",
  "71": "Noah",
  "72": "Jinns",
  "73": "Cloaked",
  "74": "The Hidden Secret",
  "75": "Resurrection",
  "76": "The Human",
  "77": "Dispatched",
  "78": "The Event",
  "79": "The Snatchers",
  "80": "He Frowned",
  "81": "The Rolling",
  "82": "The Shattering",
  "83": "The Cheaters",
  "84": "The Rupture",
  "85": "The Galaxies",
  "86": "The Bright Star",
  "87": "The Most High",
  "88": "Overwhelming",
  "89": "Dawn",
  "90": "The Town",
  "91": "The Sun",
  "92": "The Night",
  "93": "The Forenoon",
  "94": "Cooling the Temper",
  "95": "The Fig",
  "96": "The Embryo",
  "97": "The Destiny",
  "98": "The Proof",
  "99": "The Quake",
  "100": "The Gallopers",
  "101": "The Shocker",
  "102": "Hoarding",
  "103": "The Afternoon",
  "104": "The Backbiter",
  "105": "The Elephant",
  "106": "Quraish Tribe",
  "107": "Charity",
  "108": "Bounty",
  "109": "The Disbelievers",
  "110": "Triumph",
  "111": "Thorns",
  "112": "Absoluteness",
  "113": "Daybreak",
  "114": "People"
};

export const APPENDIX_TITLES_EN: Record<number, string> = {
  "1": "One of the Great Miracles [74:35]",
  "2": "God's Messenger of the Covenant [3:81]",
  "3": "We Made the Quran Easy [54:17]",
  "4": "Why Was the Quran Revealed in Arabic?",
  "5": "Heaven and Hell",
  "6": "Greatness of God",
  "7": "Why Were We Created?",
  "8": "The Myth of Intercession",
  "9": "Abraham: Original Messenger of Submission",
  "10": "God's Usage of the Plural Tense",
  "11": "The Day of Resurrection",
  "12": "Role of the Prophet Muhammad",
  "13": "The First Pillar of Submission",
  "14": "Predestination",
  "15": "Religious Duties: Gift from God",
  "16": "Dietary Prohibition",
  "17": "Death",
  "18": "Quran is All You Need",
  "19": "Hadith and Sunna: Satanic Innovations",
  "20": "Quran: Unlike Any Other Book",
  "21": "Satan: Fallen Angel",
  "22": "Jesus",
  "23": "Chronological Order of Revelation",
  "24": "Two False Verses Removed from the Quran",
  "25": "End of the World",
  "26": "The Three Messengers of Islam",
  "27": "Who Is Your God?",
  "28": "Muhammad Wrote God's Revelations With His Own Hand",
  "29": "The Missing Basmalah",
  "30": "Polygamy",
  "31": "Evolution: A Divinely Guided Process",
  "32": "The Crucial Age of 40",
  "33": "Why Did God Send a Messenger Now?",
  "34": "Virginity/Chastity: A Trait of the True Believers",
  "35": "Drugs & Alcohol",
  "36": "What Price A Great Nation",
  "37": "Criminal Justice in Islam",
  "38": "The Creator's Signature"
};
