/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List supported languages
         * @description Returns all languages supported by the API, including the internal integer `id`, the ISO 639-1 `code` (used as a key in translation maps), the human-readable `name`, and the text `direction` (`ltr` or `rtl`). Use the `code` values from this endpoint as valid values for any `langs` or `word_langs` parameter throughout the API.
         */
        get: operations["getLanguages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch chapter metadata
         * @description Returns metadata for all 114 Quranic chapters: chapter number, verse count, revelation order, and the chapter title in the requested language. If `lang` is omitted the title is returned in the default language (English). Use this endpoint to build a chapter-picker UI or map chapter numbers to human-readable titles.
         */
        get: operations["getChapters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appendices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch appendix metadata
         * @description Returns metadata for all Quranic appendices: a numeric code, a title, and a short snippet. If `lang` is omitted the title and snippet are returned in the default language (English).
         */
        get: operations["getAppendices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quran": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch a range of verses
         * @description Returns a contiguous range of Quranic verses in one or more languages simultaneously. Two selection modes are supported:
         *     **Range mode** — use `chapter_number_start`, `verse_start`, `verse_end`, and optionally `chapter_number_end` to specify a span.
         *     **Compact mode** — use the `verses` parameter with a shorthand reference string. When `verses` is present it takes priority over all range params.
         *     Optional word-level data (Arabic text, root, meaning) can be added with `include_words`, `include_root`, and `include_meaning`.
         */
        get: operations["getQuran"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full-text search across the Quran
         * @description Full-text search across verse translations and chapter titles in all indexed languages. Supports fuzzy / partial matching via `pg_trgm`.
         *     **Scope `verses` (default)** — searches the translated text of each verse. Returns verses ranked by FTS relevance, optionally boosted by vector similarity when `semantic=true`.
         *     **Scope `words`** — searches word-level Arabic / transliteration text. When `root` is also provided with `scope=words`, an exact root match is performed instead of FTS.
         *     Results are paginated with `limit` / `offset`. Use the `total` field in the response envelope to calculate page count.
         */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Paginated roots index
         * @description Returns a paginated list of distinct Arabic roots aggregated from `word_text.word_root`, with per-root occurrence counts and a server-computed Latin Buckwalter transliteration (`tr`).
         *     Supports three sort modes (`frequency`, `abjadi`, `reverse`) and an optional Arabic prefix filter. Use `limit` / `offset` for pagination; `total` reflects the filtered universe so page count is consistent.
         */
        get: operations["getRoots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roots/{letters}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full root record
         * @description Returns full metadata for a single root: count, transliteration, distinct derived surface forms (`dv`), and the first 20 occurrences (`oc`). Use `/roots/{letters}/occurrences` to paginate beyond the first 20.
         */
        get: operations["getRootDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roots/{letters}/occurrences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Paginated occurrences for a single root
         * @description Returns paginated verse occurrences for the given root, ordered by canonical reading order (`global_index`). Use `total` for page count.
         */
        get: operations["getRootOccurrences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bible/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all Bible books
         * @description Returns summary metadata for all 66 canonical Bible books: book number, book name, testament (`OT` or `NT`), chapter count, and total verse count. Use `bn` (book_number) from this list as the `book` parameter in `/bible`.
         */
        get: operations["getBibleBooks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bible": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch Bible verses by range
         * @description Returns verses for a specific Bible book and chapter/verse range in one or more languages simultaneously. The response groups verses by book and chapter, mirroring the `/quran` response structure.
         *     To fetch an entire chapter, supply only `book` and `chapter_start` — the server defaults `verse_start` to 1 and `verse_end` to the last verse.
         *     To fetch a single verse, supply `book`, `chapter_start`, `verse_start`, and set `verse_end` equal to `verse_start`.
         */
        get: operations["getBible"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bible/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full-text search across the Bible
         * @description Full-text search over Bible verse content and footnotes. Results are grouped by book and chapter, ordered by relevance score descending. Paginate with `limit` and `offset`; use the `total` field in the response envelope to compute total pages.
         */
        get: operations["searchBible"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/music/artists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all music artists
         * @description Returns all artists in the music catalogue, ordered by `display_priority` ascending (lower number = shown first). Use `id` to filter albums and tracks by artist.
         */
        get: operations["getMusicArtists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/music/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all music categories
         * @description Returns all music categories (genres / themes), ordered by `display_priority` ascending. Use `id` to filter tracks by category.
         */
        get: operations["getMusicCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/music/albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List music albums
         * @description Returns all albums, optionally filtered by artist. Albums are returned in no guaranteed order; sort client-side by `release_date` or `name` as needed.
         */
        get: operations["getMusicAlbums"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/music/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List music tracks
         * @description Returns tracks, with optional filters for artist, category, album, and featured status. Multiple filters can be combined — they are applied as AND conditions. Omit all filters to retrieve the full catalogue.
         */
        get: operations["getMusicTracks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/communities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List communities (online and physical)
         * @description Returns active community entries authored in Sanity (online communities on platforms like Discord/Telegram, plus physical meet-up locations). Backed by the Sanity content lake; results are cached server-side and invalidated by webhook on document changes.
         */
        get: operations["getCommunities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Top-level envelope for both `/quran` (reader) and `/search` (FTS) responses. The `info` object describes the query parameters that were resolved; `chapters` contains the matching verses grouped by chapter. */
        QuranResponse: {
            info?: components["schemas"]["QuranResponseInfo"];
            chapters?: components["schemas"]["ChapterData"][];
        };
        /** @description Metadata envelope describing the resolved query. Reader fields (`chapter_start`, `chapter_end`, `verse_start`, `verse_end`) are populated by `/quran` and absent from `/search` responses. Search fields (`q`, `total`, `limit`, `offset`, `scope`) are populated by `/search` and absent from `/quran` responses. */
        QuranResponseInfo: {
            /**
             * @description Number of verses returned in this response page. For `/quran` this equals the total number of matching verses (no pagination); for `/search` this is the number of verses on the current page (≤ `limit`).
             * @example 7
             */
            result_count?: number;
            /**
             * @description Resolved first chapter of the query range (reader only). Reflects the `chapter_number_start` param after server validation.
             * @example 2
             */
            chapter_start?: number;
            /**
             * @description Resolved last chapter of the query range (reader only). Equal to `chapter_start` when no end chapter was requested.
             * @example 2
             */
            chapter_end?: number;
            /**
             * @description Resolved first verse of the query range (reader only). Defaults to 1 when the param was omitted.
             * @example 1
             */
            verse_start?: number;
            /**
             * @description Resolved last verse of the query range (reader only). Defaults to the final verse of the chapter when the param was omitted.
             * @example 7
             */
            verse_end?: number;
            /**
             * @description The search query as submitted by the client (search only).
             * @example mercy of God
             */
            q?: string;
            /**
             * @description Total number of matching verses across ALL pages (search only). Use together with `limit` and `offset` to calculate the total page count and navigate paginated results.
             * @example 42
             */
            total?: number;
            /**
             * @description Page size used for this response (search only).
             * @example 20
             */
            limit?: number;
            /**
             * @description Number of results skipped before this page (search only).
             * @example 0
             */
            offset?: number;
            /**
             * @description Search scope that was applied (search only). `verses` means verse translation text was searched; `words` means word-level Arabic / transliteration text was searched.
             * @example verses
             */
            scope?: string;
        };
        /** @description A single Quranic chapter with its matching verses. In reader mode all verses within the requested range are included. In search mode only verses that matched the query are included, and the `hits` and `tm` fields are populated. */
        ChapterData: {
            /**
             * @description chapter_number — Quranic chapter number, 1-based (1–114).
             * @example 1
             */
            cn?: number;
            /**
             * @description Map of chapter titles keyed by ISO 639-1 language code. Only codes that were requested in `langs` (or all available codes for `/chapters`) are present.
             * @example {
             *       "en": "The Opening",
             *       "ar": "الفاتحة"
             *     }
             */
            titles?: {
                [key: string]: string;
            };
            verses?: components["schemas"]["VerseData"][];
            /**
             * @description Number of verses in this chapter that matched the search query (search only). Absent from `/quran` responses.
             * @example 3
             */
            hits?: number;
            /**
             * @description title_match — `true` when the chapter title itself matched the search query, not just verse content (search only). Absent from `/quran` responses.
             * @example false
             */
            tm?: boolean;
        };
        /** @description A single Quranic verse with its translations in the requested languages, and optionally word-by-word data. */
        VerseData: {
            /**
             * @description verse_index — 0-based position of this verse within its chapter. The first verse (`vi: 0`) is verse 1.
             * @example 0
             */
            vi?: number;
            /**
             * @description verse_key — `chapter_number:verse_number` (1-based), e.g. `2:255` for Ayat al-Kursi or `1:1` for the Fatiha opening verse.
             * @example 1:1
             */
            vk?: string;
            /**
             * Format: float
             * @description Relevance score assigned by the FTS / semantic ranker (search only). Higher values indicate stronger relevance to the query. Absent from `/quran` responses.
             * @example 0.87
             */
            sc?: number;
            /** @description Translations keyed by ISO 639-1 language code. Only the codes requested via `langs` are present. Example: `{ "en": { ... }, "ar": { ... } }`. */
            tr?: {
                [key: string]: components["schemas"]["TranslationContent"];
            };
            /** @description Word-by-word breakdown of the verse (present only when `include_words=true`). Each element represents one Arabic word in reading order. */
            w?: components["schemas"]["WordData"][];
        };
        /** @description A single translation of a verse in one language. All short field names follow the minified key convention documented in the info section. */
        TranslationContent: {
            /**
             * @description lang_id — internal integer identifier for this language.
             * @example 1
             */
            li?: number;
            /**
             * @description lang_code — ISO 639-1 language code, e.g. `en`, `ar`, `fr`.
             * @example en
             */
            lc?: string;
            /**
             * @description direction — text direction for this language. `ltr` for Latin-script languages (English, French, …); `rtl` for Arabic, Hebrew, Urdu, etc.
             * @example ltr
             * @enum {string}
             */
            d?: "ltr" | "rtl";
            /**
             * @description Full translation text of this verse in this language.
             * @example In the name of God, the Gracious, the Merciful.
             */
            tx?: string;
            /**
             * @description subtitle — chapter-level subtitle or section heading associated with this verse (Quran-specific, nullable). Typically appears only on verse 1 of a chapter.
             * @example null
             */
            s?: string | null;
            /**
             * @description footer — translator's footnote or clarification appended after the verse text (nullable). May contain cross-references or explanatory notes.
             * @example null
             */
            f?: string | null;
            /**
             * @description Highlighted snippet with `<b>…</b>` tags wrapping the matched terms (search only). Suitable for rendering search result previews. `null` in `/quran` responses.
             * @example In the name of <b>God</b>, the Gracious, the Merciful.
             */
            hl?: string | null;
        };
        /** @description Data for a single Arabic word within a verse. Returned only when `include_words=true`. Fields `r` and `m` require their respective `include_root` / `include_meaning` params to be `true`. */
        WordData: {
            /**
             * @description word_index — 0-based position of this word within its verse. The first word of the verse is `wi: 0`.
             * @example 0
             */
            wi?: number;
            /**
             * @description global_index — unique 1-based index of this word across the entire Quran (all chapters, all verses, in reading order).
             * @example 1
             */
            gi?: number;
            /**
             * @description Word text keyed by language code (e.g. `{ "ar": "بِسْمِ" }`). Only codes requested via `word_langs` are present. `null` if no `word_langs` were requested.
             * @example {
             *       "ar": "بِسْمِ"
             *     }
             */
            tx?: {
                [key: string]: string;
            } | null;
            /**
             * @description Highlighted word text keyed by language code, with `<b>` tags around the matched portion (word search only). `null` for non-search responses or when the word did not match.
             * @example null
             */
            hl?: {
                [key: string]: string;
            } | null;
            /**
             * @description root — Arabic root of the word (3–4 letter root form, e.g. `رحم` for words related to mercy). `null` unless `include_root=true`.
             * @example سمو
             */
            r?: string | null;
            /**
             * @description meaning — English gloss / meaning of this specific word form (e.g. `"in the name of"`). `null` unless `include_meaning=true`.
             * @example in the name of
             */
            m?: string | null;
            /**
             * @description Arbitrary metadata object containing morphological tags, grammar notes, or other word-level annotations. Structure may vary and should be treated as opaque unless documented separately.
             * @example null
             */
            meta?: Record<string, never> | null;
        };
        /** @description Compact record for one Quranic Arabic root, returned by the index endpoint. `r` is the storage form (space-separated Arabic letters); `tr` is the server-computed Latin Buckwalter transliteration joined with hyphens (e.g. `k-t-b`). `s` is reserved for an editorial sense gloss and is always `null` until Phase 2 morphology data lands. */
        RootSummary: {
            /**
             * @description Root letters, space-separated Arabic (storage form).
             * @example ك ت ب
             */
            r: string;
            /**
             * @description Latin Buckwalter transliteration of the root, lowercase letters joined with `-`. Computed server-side from `r`.
             * @example k-t-b
             */
            tr: string;
            /**
             * @description Editorial sense gloss for this root (Phase 2; always `null` for now).
             * @example null
             */
            s?: string | null;
            /**
             * @description Total occurrence count of this root across the corpus.
             * @example 319
             */
            c: number;
        };
        /** @description Full record for one root, including derived surface forms (`dv`) and the first 20 verse occurrences (`oc`). Paginate beyond 20 via `/roots/{letters}/occurrences`. */
        RootRecord: components["schemas"]["RootSummary"] & {
            /** @description Distinct derived surface forms of this root, capped at 20 and ordered by descending count. */
            dv?: components["schemas"]["Derivative"][];
            /** @description First 20 verse occurrences of this root, ordered by canonical reading order (`global_index`). */
            oc?: components["schemas"]["Occurrence"][];
            /**
             * @description Morphology note for the root (Phase 2; always `null` for now).
             * @example null
             */
            mp?: string | null;
            /**
             * @description Per-root meaning string. The `meaning` column in `word_text` is denormalized — every surface form sharing this root carries the same string. The server returns one canonical row's value here. Senses are typically separated by `;`. May be `null` when no English meaning row exists for the root.
             * @example to write; note; record; collect; book; writing; scripture; decree; letter
             */
            m?: string | null;
        };
        /** @description A distinct surface form (token spelling) of a root, with its occurrence count. `tr` is the Latin transliteration of the surface form, sourced from `word_text` rows tagged with the `tl` language (most-common value when multiple readings exist). `en` and `p` (POS) remain reserved for Phase 2 morphology data and are still `null`. */
        Derivative: {
            /**
             * @description Surface form (Arabic word as it appears in the corpus).
             * @example كِتَاب
             */
            ar: string;
            /**
             * @description Latin transliteration of the surface form (e.g. "kitāb"). Drawn from the per-word `tl` entry in `word_text`. May be `null` if no transliteration row exists for that word.
             * @example kitāb
             */
            tr?: string | null;
            /**
             * @description English gloss for this surface form (Phase 2; always `null`).
             * @example null
             */
            en?: string | null;
            /**
             * @description Number of occurrences of this exact surface form.
             * @example 56
             */
            c: number;
            /**
             * @description Part-of-speech tag (Phase 2; always `null`).
             * @example null
             * @enum {string|null}
             */
            p?: "V" | "N" | "ADJ" | "PASS" | "PRO" | "NEG" | "P" | "REL" | null;
        };
        /** @description One verse occurrence of a root. `vk` is the verse_key (`chapter_number:verse_number`); `ar` is the full Arabic verse text; `en` is the primary English translation when available; `hl` is the exact surface form to highlight inside `ar` on the client. */
        Occurrence: {
            /**
             * @description verse_key — `chapter_number:verse_number`, both 1-based.
             * @example 2:282
             */
            vk: string;
            /**
             * @description Full Arabic verse text.
             * @example يَا أَيُّهَا الَّذِينَ آمَنُوا إِذَا تَدَايَنتُم بِدَيْنٍ ...
             */
            ar: string;
            /**
             * @description Primary English translation of the verse (nullable).
             * @example O you who believe, when you transact a loan ...
             */
            en?: string | null;
            /**
             * @description Surface form (matched word) to highlight inside `ar`. Best-effort: the client may need to handle diacritics when locating the substring.
             * @example كِتَاب
             */
            hl?: string | null;
            /**
             * @description Latin transliteration of the matched surface form (`hl`). Drawn from the per-word `tl` entry in `word_text`. May be `null` if no transliteration row exists for that word.
             * @example kitāb
             */
            tl?: string | null;
            /**
             * @description 1-based word index of the matched word inside its verse. Lets the client highlight the exact token without resorting to substring matching (which mis-targets short surface forms like `مِن` that embed inside longer words like `مُؤْمِن`).
             * @example 4
             */
            wi?: number | null;
        };
        /** @description Paginated index of roots returned by `/roots`. */
        RootsIndexResponse: {
            items: components["schemas"]["RootSummary"][];
            /**
             * @description Total number of distinct roots matching the optional `q` filter.
             * @example 1689
             */
            total: number;
        };
        /** @description Paginated occurrences for a single root. */
        OccurrencesResponse: {
            items: components["schemas"]["Occurrence"][];
            /**
             * @description Total number of occurrences of this root in the corpus.
             * @example 319
             */
            total: number;
        };
        /** @description A language supported by the API for translations and word text. */
        Language: {
            /**
             * @description Internal integer identifier. Used internally; prefer `code` for all API calls.
             * @example 1
             */
            id?: number;
            /**
             * @description ISO 639-1 language code. Use this value in `langs`, `word_langs`, and `lang` parameters throughout the API.
             * @example en
             */
            code?: string;
            /**
             * @description Human-readable language name in English.
             * @example English
             */
            name?: string;
            /**
             * @description Text direction for this language. `ltr` for left-to-right scripts; `rtl` for right-to-left scripts (Arabic, Hebrew, Urdu, Persian).
             * @example ltr
             * @enum {string}
             */
            direction?: "ltr" | "rtl";
        };
        /** @description List of metadata objects for all 114 Quranic chapters. */
        ChapterMetadata: components["schemas"]["Chapter"][];
        /** @description Metadata for a single Quranic chapter. */
        Chapter: {
            /**
             * @description Chapter number, 1-based (1–114). Also known as Surah number.
             * @example 1
             */
            chapter_number?: number;
            /**
             * @description Total number of verses in this chapter.
             * @example 7
             */
            verse_count?: number;
            /**
             * @description Chronological order in which the chapter was revealed (1-based). Distinct from the canonical chapter_number ordering.
             * @example 5
             */
            revelation_order?: number;
            /**
             * @description Chapter title in the language requested via the `lang` parameter (or the default language if omitted).
             * @example The Opening
             */
            title?: string;
        };
        /** @description List of metadata objects for all Quranic appendices. */
        AppendixMetadata: components["schemas"]["Appendix"][];
        /** @description Metadata for a single Quranic appendix. */
        Appendix: {
            /**
             * @description Numeric code identifying the appendix.
             * @example 1
             */
            code?: number;
            /**
             * @description Title of the appendix in the requested language.
             * @example God's Attributes
             */
            title?: string;
            /**
             * @description Short introductory excerpt from the appendix body.
             * @example The Quran teaches that God is One...
             */
            snippet?: string;
        };
        /** @description Top-level envelope for both `/bible` (reader) and `/bible/search` (FTS) responses. The `info` object describes the resolved query; `books` contains the matching verses grouped by book and chapter. */
        BibleResponse: {
            info?: components["schemas"]["BibleResponseInfo"];
            books?: components["schemas"]["BibleBookData"][];
        };
        /** @description Metadata envelope for Bible responses. Reader fields (`book`, `chapter_start`, `chapter_end`, `verse_start`, `verse_end`) are populated by `/bible`; search fields (`q`, `total`, `limit`, `offset`) are populated by `/bible/search`. */
        BibleResponseInfo: {
            /**
             * @description Number of verses returned in this response page.
             * @example 12
             */
            result_count?: number;
            /**
             * @description Requested book number (reader only). 1-based: 1 = Genesis, 40 = Matthew, 66 = Revelation.
             * @example 40
             */
            book?: number;
            /**
             * @description Resolved first chapter of the query range (reader only).
             * @example 5
             */
            chapter_start?: number;
            /**
             * @description Resolved last chapter of the query range (reader only).
             * @example 5
             */
            chapter_end?: number;
            /**
             * @description Resolved first verse of the query range (reader only).
             * @example 1
             */
            verse_start?: number;
            /**
             * @description Resolved last verse of the query range (reader only).
             * @example 12
             */
            verse_end?: number;
            /**
             * @description The search query as submitted (search only).
             * @example blessed are the meek
             */
            q?: string;
            /**
             * @description Total matching results across all pages (search only). Use with `limit` and `offset` for pagination.
             * @example 15
             */
            total?: number;
            /**
             * @description Page size used for this response (search only).
             * @example 20
             */
            limit?: number;
            /**
             * @description Number of results skipped before this page (search only).
             * @example 0
             */
            offset?: number;
        };
        /** @description Summary metadata for one Bible book, as returned by `/bible/books`. */
        BibleBook: {
            /**
             * @description book_number — 1-based index: 1 = Genesis, 40 = Matthew, 66 = Revelation. Use this value as the `book` parameter in `/bible`.
             * @example 40
             */
            bn?: number;
            /**
             * @description book_name — full English name of the book.
             * @example Matthew
             */
            bk?: string;
            /**
             * @description testament — `OT` for Old Testament (books 1–39), `NT` for New Testament (books 40–66).
             * @example NT
             */
            t?: string;
            /**
             * @description chapter_count — total number of chapters in this book.
             * @example 28
             */
            cc?: number;
            /**
             * @description verse_count — total number of verses in this book.
             * @example 1071
             */
            vc?: number;
        };
        /** @description A Bible book with nested chapters returned by `/bible` and `/bible/search`. In reader mode all chapters/verses in the requested range are included. In search mode only chapters/verses that matched the query are included. */
        BibleBookData: {
            /**
             * @description book_number — 1-based book index (1 = Genesis … 66 = Revelation).
             * @example 40
             */
            bn?: number;
            /**
             * @description book_name — full English name of the book.
             * @example Matthew
             */
            bk?: string;
            /**
             * @description testament — `OT` for Old Testament (books 1–39), `NT` for New Testament (books 40–66).
             * @example NT
             */
            t?: string;
            chapters?: components["schemas"]["BibleChapterData"][];
        };
        /** @description A single Bible chapter with its matching verses. */
        BibleChapterData: {
            /**
             * @description chapter_number — 1-based chapter number within the book.
             * @example 5
             */
            cn?: number;
            /**
             * @description Number of verses in this chapter that matched the search query (search only). Absent from `/bible` reader responses.
             * @example 4
             */
            hits?: number;
            verses?: components["schemas"]["BibleVerseData"][];
        };
        /** @description A single Bible verse with its translations and optional relevance score. */
        BibleVerseData: {
            /**
             * @description verse_number — 1-based verse number within its chapter.
             * @example 3
             */
            vn?: number;
            /**
             * @description verse_key — `book_number:chapter_number:verse_number` (all 1-based), e.g. `40:5:3` for Matthew 5:3 or `1:1:1` for Genesis 1:1.
             * @example 40:5:3
             */
            vk?: string;
            /**
             * Format: float
             * @description Relevance score assigned by the FTS ranker (search only). Higher values indicate stronger relevance. Absent from `/bible` responses.
             * @example 0.92
             */
            sc?: number;
            /** @description Translations keyed by ISO 639-1 language code. Only the codes requested via `langs` are present. */
            tr?: {
                [key: string]: components["schemas"]["BibleTranslationContent"];
            };
        };
        /** @description A single translation of a Bible verse in one language. Field names follow the same minified key convention as the Quran API. */
        BibleTranslationContent: {
            /**
             * @description lang_id — internal integer identifier for this language.
             * @example 1
             */
            li?: number;
            /**
             * @description lang_code — ISO 639-1 language code, e.g. `en`.
             * @example en
             */
            lc?: string;
            /**
             * @description direction — text direction for this language. `ltr` for Latin scripts; `rtl` for Arabic / Hebrew.
             * @example ltr
             * @enum {string}
             */
            d?: "ltr" | "rtl";
            /**
             * @description Full translation text of this verse in this language.
             * @example Blessed are the meek, for they will inherit the earth.
             */
            tx?: string;
            /**
             * @description footer — short translator's footnote or clarification appended after the verse text (nullable).
             * @example null
             */
            f?: string | null;
            /**
             * @description Theological footnotes — array of extended commentary strings (nullable). Distinct from `f` (short inline footnote): `fn` entries are longer annotations, cross-references, or theological explanations associated with this verse.
             * @example null
             */
            fn?: string[] | null;
            /**
             * @description Highlighted snippet with `<b>…</b>` tags wrapping matched terms (search only). `null` in `/bible` reader responses.
             * @example Blessed are the <b>meek</b>, for they will inherit the earth.
             */
            hl?: string | null;
        };
        /** @description A music artist in the catalogue. */
        MusicArtist: {
            /**
             * @description Internal artist identifier. Use this as `artist_id` in albums and tracks filters.
             * @example 1
             */
            id: number;
            /**
             * @description Display name of the artist.
             * @example Maher Zain
             */
            name: string;
            /**
             * @description Short biography or description of the artist (nullable).
             * @example Swedish-Lebanese singer and songwriter of Islamic music.
             */
            description?: string | null;
            /**
             * @description URL to the artist's cover / profile image.
             * @example https://cdn.wikisubmission.org/artists/maher-zain.jpg
             */
            image_url: string;
            /**
             * @description Sort order for display; lower values appear first.
             * @example 1
             */
            display_priority: number;
        };
        /** @description A music category (genre / theme) used to classify tracks. */
        MusicCategory: {
            /**
             * @description Internal category identifier. Use this as `category_id` in the tracks filter.
             * @example 1
             */
            id: number;
            /**
             * @description Display name of the category.
             * @example Nasheed
             */
            name: string;
            /**
             * @description Short description of the category (nullable).
             * @example Vocal-only Islamic devotional music.
             */
            description?: string | null;
            /**
             * @description Sort order for display; lower values appear first.
             * @example 1
             */
            display_priority: number;
        };
        /** @description A music album in the catalogue. */
        MusicAlbum: {
            /**
             * @description Internal album identifier. Use this as `album_id` in the tracks filter.
             * @example 1
             */
            id: number;
            /**
             * @description Album title.
             * @example Thank You Allah
             */
            name: string;
            /**
             * @description ID of the artist this album belongs to. Matches `id` in `MusicArtist`.
             * @example 1
             */
            artist_id: number;
            /**
             * Format: date
             * @description Album release date in ISO 8601 format (`YYYY-MM-DD`).
             * @example 2009-01-01
             */
            release_date: string;
            /**
             * @description Short description of the album (nullable).
             * @example null
             */
            description?: string | null;
        };
        /** @description A single music track in the catalogue. */
        MusicTrack: {
            /**
             * @description Internal track identifier.
             * @example 1
             */
            id: number;
            /**
             * @description Track title.
             * @example Thank You Allah
             */
            name: string;
            /**
             * Format: date
             * @description Track release date in ISO 8601 format (`YYYY-MM-DD`).
             * @example 2009-01-01
             */
            release_date: string;
            /**
             * @description Direct URL to the audio file or streaming resource.
             * @example https://cdn.wikisubmission.org/music/thank-you-allah.mp3
             */
            url: string;
            /**
             * @description ID of the artist. Matches `id` in `MusicArtist`.
             * @example 1
             */
            artist_id: number;
            /**
             * @description ID of the category (nullable). Matches `id` in `MusicCategory`.
             * @example 1
             */
            category_id?: number | null;
            /**
             * @description ID of the album (nullable). Matches `id` in `MusicAlbum`.
             * @example 1
             */
            album_id?: number | null;
            /**
             * @description Whether this track is hand-picked as featured. Featured tracks are highlighted in the UI and can be filtered with `featured=true`.
             * @example false
             */
            featured: boolean;
            /**
             * @description Full song lyrics (nullable). May contain newlines for line breaks.
             * @example null
             */
            lyrics?: string | null;
        };
        /** @description Latitude/longitude pair for a physical community. */
        GeoPoint: {
            /**
             * Format: double
             * @example 36.7525
             */
            lat?: number;
            /**
             * Format: double
             * @example 3.042
             */
            lng?: number;
        };
        /** @description A community entry sourced from Sanity. The `kind` discriminator determines which optional fields are populated: `online` communities carry `platform`/`url`/`inviteCode`/`memberCount`; `physical` communities carry `address`/`city`/`country`/`geo`/`contactEmail`/ `contactPhone`/`meetingSchedule`. The `imageUrl`, when present, points at the ws-backend image proxy and not directly at Sanity's CDN. */
        Community: {
            /**
             * @description Sanity document ID.
             * @example drafts.community-foo
             */
            _id: string;
            /**
             * @example online
             * @enum {string}
             */
            kind: "online" | "physical";
            /** @example Submitters Discord */
            name: string;
            /** @example submitters-discord */
            slug?: string;
            /**
             * @description ISO 639-1 language code.
             * @example en
             */
            language?: string;
            description?: string;
            /**
             * @description Proxied image URL routed through `/sanity/image/...`. Preserves Sanity's image transform query string when present.
             * @example /sanity/image/abc123-1024x768.jpg
             */
            imageUrl?: string;
            tags?: string[];
            /** @example true */
            isActive: boolean;
            /**
             * @example discord
             * @enum {string}
             */
            platform?: "discord" | "telegram" | "whatsapp" | "facebook" | "x" | "youtube" | "other";
            /** Format: uri */
            url?: string;
            inviteCode?: string;
            memberCount?: number;
            address?: string;
            city?: string;
            /** @description ISO 3166-1 alpha-2 country code. */
            country?: string;
            geo?: components["schemas"]["GeoPoint"];
            /** Format: email */
            contactEmail?: string;
            contactPhone?: string;
            meetingSchedule?: string;
        };
    };
    responses: {
        /** @description The request could not be completed due to a conflict with the current state of the resource. Resolve the conflict and try again. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    message: string;
                };
            };
        };
        /** @description The server cannot find the requested resource. The endpoint may be invalid or the resource may no longer exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    message: string;
                };
            };
        };
        /** @description The server could not understand the request due to invalid syntax. The client should modify the request and try again. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    message: string;
                };
            };
        };
        /** @description The server encountered an unexpected condition that prevented it from fulfilling the request. Report the issue to the support team if it persists. */
        InternalServerErrror: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    message: string;
                };
            };
        };
        /** @description The requested operation is not yet implemented. */
        NotImplementedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example This endpoint is under development. */
                    message: string;
                    /** @example NOT_IMPLEMENTED */
                    code: string;
                };
            };
        };
        /** @description The upstream content source (Sanity) returned an error or was unreachable. The response is structurally valid but the request could not be fulfilled. */
        BadGateway: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    message: string;
                };
            };
        };
    };
    parameters: {
        /**
         * @description Language codes for word-level text. Must be a subset of the `langs` array. Only words in these languages are included in the `tx` map of each `WordData` object. Typically set to `["ar"]` to include Arabic word text alongside an English translation.
         * @example [
         *       "ar"
         *     ]
         */
        WordLangsParam: string[];
        /**
         * @description When `true`, each verse includes a `w` array of `WordData` objects with per-word text (and optionally root / meaning). When `false` (default), the `w` array is entirely omitted from each verse, keeping the response compact.
         * @example false
         */
        IncludeWordsParam: boolean;
        /**
         * @description When `true`, each `WordData` object includes the `r` field containing the Arabic root (3–4 letters). Requires `include_words=true`. Has no effect when `include_words=false`.
         * @example false
         */
        IncludeRootParam: boolean;
        /**
         * @description When `true`, each `WordData` object includes the `m` field containing an English gloss / meaning for the word. Requires `include_words=true`. Has no effect when `include_words=false`.
         * @example false
         */
        IncludeMeaningParam: boolean;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLanguages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Language"][];
                };
            };
            500: components["responses"]["InternalServerErrror"];
        };
    };
    getChapters: {
        parameters: {
            query?: {
                /**
                 * @description ISO 639-1 language code for the chapter title (e.g. `en`, `ar`, `fr`). Must be a code returned by `/languages`. Defaults to `en` when omitted.
                 * @example en
                 */
                lang?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterMetadata"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerErrror"];
            501: components["responses"]["NotImplementedError"];
        };
    };
    getAppendices: {
        parameters: {
            query?: {
                /**
                 * @description ISO 639-1 language code for the appendix title and snippet (e.g. `en`, `ar`). Must be a code returned by `/languages`.
                 * @example en
                 */
                lang?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppendixMetadata"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerErrror"];
            501: components["responses"]["NotImplementedError"];
        };
    };
    getQuran: {
        parameters: {
            query: {
                /**
                 * @description First (or only) chapter to include, 1-based (1–114). When `chapter_number_end` is omitted, only this chapter is queried. Ignored when `verses` is provided.
                 * @example 2
                 */
                chapter_number_start?: number;
                /**
                 * @description Last chapter to include (inclusive), 1-based (1–114). Must be ≥ `chapter_number_start`. Ignored when `verses` is provided.
                 * @example 2
                 */
                chapter_number_end?: number;
                /**
                 * @description First verse to include within `chapter_number_start`. Use `0` for the Basmallah; `1` and above for numbered verses. Defaults to 1 when omitted. Ignored when `verses` is provided.
                 * @example 1
                 */
                verse_start?: number;
                /**
                 * @description Last verse to include within `chapter_number_end` (or `chapter_number_start` if no end chapter), 1-based. Defaults to the last verse of the chapter when omitted. Ignored when `verses` is provided.
                 * @example 5
                 */
                verse_end?: number;
                /**
                 * @description Compact verse reference string. Takes priority over all chapter/verse range params when present. Supported formats:
                 *     - Single verse: `1:1` - Range within a chapter: `1:1-7` - Comma-separated list: `1:2,2:255,2:285-286`
                 *     Maximum 300 verses per request.
                 * @example 2:255,2:285-286
                 */
                verses?: string;
                /**
                 * @description One or more ISO 639-1 language codes to include in the response. Each code must be a value returned by `/languages`. Translations for each code appear inside every verse's `tr` map.
                 * @example [
                 *       "en",
                 *       "ar"
                 *     ]
                 */
                langs: string[];
                /**
                 * @description Language codes for word-level text. Must be a subset of the `langs` array. Only words in these languages are included in the `tx` map of each `WordData` object. Typically set to `["ar"]` to include Arabic word text alongside an English translation.
                 * @example [
                 *       "ar"
                 *     ]
                 */
                word_langs?: components["parameters"]["WordLangsParam"];
                /**
                 * @description When `true`, each verse includes a `w` array of `WordData` objects with per-word text (and optionally root / meaning). When `false` (default), the `w` array is entirely omitted from each verse, keeping the response compact.
                 * @example false
                 */
                include_words?: components["parameters"]["IncludeWordsParam"];
                /**
                 * @description When `true`, each `WordData` object includes the `r` field containing the Arabic root (3–4 letters). Requires `include_words=true`. Has no effect when `include_words=false`.
                 * @example false
                 */
                include_root?: components["parameters"]["IncludeRootParam"];
                /**
                 * @description When `true`, each `WordData` object includes the `m` field containing an English gloss / meaning for the word. Requires `include_words=true`. Has no effect when `include_words=false`.
                 * @example false
                 */
                include_meaning?: components["parameters"]["IncludeMeaningParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuranResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerErrror"];
            501: components["responses"]["NotImplementedError"];
        };
    };
    search: {
        parameters: {
            query?: {
                /**
                 * @description Search query (2–200 characters). Supports quoted phrases and exclusions (e.g. `"mercy of God" -punishment`). Required unless `root` is provided with `scope=words`.
                 * @example mercy of God
                 */
                q?: string;
                /**
                 * @description Arabic root string (3–4 letters, e.g. `رحم`). When provided with `scope=words`, performs an exact match on `word_root` instead of running FTS. Takes priority over `q`.
                 * @example رحم
                 */
                root?: string;
                /**
                 * @description ISO 639-1 language codes to search in. When omitted, all indexed languages are searched simultaneously. Only affects which translation columns are queried — returned verse objects always include the translations for these codes.
                 * @example [
                 *       "en"
                 *     ]
                 */
                langs?: string[];
                /**
                 * @description Whether to search verse translations (`verses`) or word-level Arabic / transliteration text (`words`). Defaults to `verses`.
                 * @example verses
                 */
                scope?: "verses" | "words";
                /**
                 * @description Maximum number of verses to return per page (1–100). Defaults to 20.
                 * @example 20
                 */
                limit?: number;
                /**
                 * @description Number of results to skip before returning the page. Use with `limit` and the `total` field for pagination.
                 * @example 0
                 */
                offset?: number;
                /**
                 * @description Enable hybrid semantic search (FTS + vector RRF fusion) when the server has an embedding model configured. Defaults to `true` when `OPENAI_API_KEY` is set, otherwise `false`. Set to `false` to force pure keyword FTS regardless of server configuration.
                 * @example true
                 */
                semantic?: boolean;
                /**
                 * @description Language codes for word-level text. Must be a subset of the `langs` array. Only words in these languages are included in the `tx` map of each `WordData` object. Typically set to `["ar"]` to include Arabic word text alongside an English translation.
                 * @example [
                 *       "ar"
                 *     ]
                 */
                word_langs?: components["parameters"]["WordLangsParam"];
                /**
                 * @description When `true`, each verse includes a `w` array of `WordData` objects with per-word text (and optionally root / meaning). When `false` (default), the `w` array is entirely omitted from each verse, keeping the response compact.
                 * @example false
                 */
                include_words?: components["parameters"]["IncludeWordsParam"];
                /**
                 * @description When `true`, each `WordData` object includes the `r` field containing the Arabic root (3–4 letters). Requires `include_words=true`. Has no effect when `include_words=false`.
                 * @example false
                 */
                include_root?: components["parameters"]["IncludeRootParam"];
                /**
                 * @description When `true`, each `WordData` object includes the `m` field containing an English gloss / meaning for the word. Requires `include_words=true`. Has no effect when `include_words=false`.
                 * @example false
                 */
                include_meaning?: components["parameters"]["IncludeMeaningParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuranResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerErrror"];
            501: components["responses"]["NotImplementedError"];
        };
    };
    getRoots: {
        parameters: {
            query?: {
                /**
                 * @description Arabic prefix filter against root letters. The frontend MUST send space-separated Arabic letters matching the storage form (e.g. `ك ت` or `ك ت ب`); Latin or Buckwalter input is not accepted on the server.
                 * @example ك ت
                 */
                q?: string;
                /**
                 * @description Ordering mode. `frequency` orders by descending occurrence count (most-attested first). `abjadi` orders by classical abjadi rank (composite over the first three letters). `reverse` is the inverse abjadi ordering.
                 * @example frequency
                 */
                sort?: "frequency" | "abjadi" | "reverse";
                /**
                 * @description Page size. Default 50. No upper bound — paginate via `offset` for large pulls.
                 * @example 50
                 */
                limit?: number;
                /**
                 * @description Number of items to skip before returning the page.
                 * @example 0
                 */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RootsIndexResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    getRootDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description URL-encoded space-separated Arabic letters of the root (e.g. `%D9%83%20%D8%AA%20%D8%A8` for `ك ت ب`). Must match the storage form exactly.
                 * @example ك ت ب
                 */
                letters: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RootRecord"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    getRootOccurrences: {
        parameters: {
            query?: {
                /**
                 * @description Page size. Default 50. No upper bound.
                 * @example 50
                 */
                limit?: number;
                /**
                 * @description Number of occurrences to skip before returning the page.
                 * @example 0
                 */
                offset?: number;
                /**
                 * @description Optional Arabic surface form filter. When provided, narrows the result set to occurrences where the matched word equals this exact string (used by the Word Lab "click derivative chip" flow). The `total` field reflects the filtered universe.
                 * @example كِتَاب
                 */
                surface?: string;
            };
            header?: never;
            path: {
                /**
                 * @description URL-encoded space-separated Arabic letters of the root.
                 * @example ك ت ب
                 */
                letters: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OccurrencesResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    getBibleBooks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BibleBook"][];
                };
            };
            500: components["responses"]["InternalServerErrror"];
        };
    };
    getBible: {
        parameters: {
            query: {
                /**
                 * @description 1-based Bible book number. 1 = Genesis, 40 = Matthew, 66 = Revelation. Use `/bible/books` to retrieve the full list of book numbers and names.
                 * @example 40
                 */
                book: number;
                /**
                 * @description First chapter to include, 1-based and within the bounds of the requested book. Use `/bible/books` to find each book's `cc` (chapter_count).
                 * @example 5
                 */
                chapter_start: number;
                /**
                 * @description Last chapter to include (inclusive), 1-based. Must be ≥ `chapter_start`. Defaults to `chapter_start` when omitted (single chapter).
                 * @example 5
                 */
                chapter_end?: number;
                /**
                 * @description First verse to include within `chapter_start`, 1-based. Defaults to 1 (beginning of the chapter) when omitted.
                 * @example 1
                 */
                verse_start?: number;
                /**
                 * @description Last verse to include within `chapter_end` (or `chapter_start`), 1-based. Defaults to the last verse of the chapter when omitted.
                 * @example 12
                 */
                verse_end?: number;
                /**
                 * @description One or more ISO 639-1 language codes to include. Each code must be returned by `/languages`. Currently the primary supported code is `en` (English).
                 * @example [
                 *       "en"
                 *     ]
                 */
                langs: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BibleResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    searchBible: {
        parameters: {
            query: {
                /**
                 * @description Search query (2–200 characters). Matched against verse text and footnotes using PostgreSQL full-text search. Supports quoted phrases.
                 * @example blessed are the meek
                 */
                q: string;
                /**
                 * @description ISO 639-1 language codes to search in. When omitted, all indexed languages are searched. Currently the primary supported code is `en`.
                 * @example [
                 *       "en"
                 *     ]
                 */
                langs?: string[];
                /**
                 * @description Maximum number of verses to return per page (1–100). Defaults to 20.
                 * @example 20
                 */
                limit?: number;
                /**
                 * @description Number of results to skip before returning the page. Use with `limit` and `total` for pagination.
                 * @example 0
                 */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BibleResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    getMusicArtists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MusicArtist"][];
                };
            };
            500: components["responses"]["InternalServerErrror"];
        };
    };
    getMusicCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MusicCategory"][];
                };
            };
            500: components["responses"]["InternalServerErrror"];
        };
    };
    getMusicAlbums: {
        parameters: {
            query?: {
                /**
                 * @description Filter results to albums belonging to this artist. Must be an `id` returned by `/music/artists`. Omit to return all albums.
                 * @example 1
                 */
                artist_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MusicAlbum"][];
                };
            };
            500: components["responses"]["InternalServerErrror"];
        };
    };
    getMusicTracks: {
        parameters: {
            query?: {
                /**
                 * @description Return only tracks by this artist. Must be an `id` returned by `/music/artists`.
                 * @example 1
                 */
                artist_id?: number;
                /**
                 * @description Return only tracks in this category. Must be an `id` returned by `/music/categories`.
                 * @example 2
                 */
                category_id?: number;
                /**
                 * @description Return only tracks from this album. Must be an `id` returned by `/music/albums`.
                 * @example 3
                 */
                album_id?: number;
                /**
                 * @description When `true`, return only featured (hand-picked) tracks. When omitted or `false`, featured and non-featured tracks are both included.
                 * @example true
                 */
                featured?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MusicTrack"][];
                };
            };
            500: components["responses"]["InternalServerErrror"];
        };
    };
    getCommunities: {
        parameters: {
            query?: {
                /**
                 * @description Filter by community kind.
                 * @example online
                 */
                kind?: "online" | "physical";
                /**
                 * @description ISO 639-1 language code of the community.
                 * @example en
                 */
                language?: string;
                /**
                 * @description ISO 3166-1 alpha-2 country code (physical communities only).
                 * @example US
                 */
                country?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Community"][];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerErrror"];
            502: components["responses"]["BadGateway"];
        };
    };
}
