/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List supported languages
         * @description Returns all languages supported by the API, including code, name, and text direction.
         */
        get: operations["getLanguages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * fetches chapter Metadata
         * @description Fetches list of quranic chapter titles, with Metadata and multilingual support
         */
        get: operations["getChapters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appendices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * fetches appendix Metadata
         * @description Fetches list of appendices, with Metadata and multilingual support
         */
        get: operations["getAppendices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quran": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch a range of verses
         * @description Returns a range of verses. Supports multiple languages simultaneously and optional word-by-word or root data.
         */
        get: operations["getQuran"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full-text search across the Quran
         * @description Full-text search across verse content and chapter titles in all indexed languages. Supports fuzzy/partial matching via pg_trgm. Scope can be narrowed to verse translations or word-level text.
         */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bible/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all Bible books
         * @description Returns all 66 Bible books with testament, chapter count, and verse count.
         */
        get: operations["getBibleBooks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bible": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch Bible verses by range
         * @description Returns verses for a specific book and chapter/verse range. Supports multiple languages simultaneously.
         */
        get: operations["getBible"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bible/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full-text search across the Bible
         * @description Full-text search over Bible verse content and footnotes. Returns results grouped by book and chapter, ordered by relevance.
         */
        get: operations["searchBible"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        QuranResponse: {
            info?: components["schemas"]["QuranResponseInfo"];
            chapters?: components["schemas"]["ChapterData"][];
        };
        /** @description Metadata envelope. Reader fields (chapter_start/end, verse_start/end) are populated by /quran; search fields (q, total, limit, offset, scope) are populated by /search. */
        QuranResponseInfo: {
            /** @description Number of matching verses in this response page. */
            result_count?: number;
            chapter_start?: number;
            chapter_end?: number;
            verse_start?: number;
            verse_end?: number;
            /** @description The search query as submitted. */
            q?: string;
            /** @description Total matching results across all pages. */
            total?: number;
            limit?: number;
            offset?: number;
            /** @description Search scope used (verses or words). */
            scope?: string;
        };
        ChapterData: {
            /** @description chapter_number */
            cn?: number;
            titles?: {
                [key: string]: string;
            };
            verses?: components["schemas"]["VerseData"][];
            /** @description Number of matching verses in this chapter (search only). */
            hits?: number;
            /** @description title_match — true when the chapter title matched the query (search only). */
            tm?: boolean;
        };
        VerseData: {
            /** @description verse_index */
            vi?: number;
            /**
             * @description verse_key
             * @example 1:1
             */
            vk?: string;
            /**
             * Format: float
             * @description Relevance score (search only).
             */
            sc?: number;
            /** @description translations keyed by language code */
            tr?: {
                [key: string]: components["schemas"]["TranslationContent"];
            };
            /** @description words */
            w?: components["schemas"]["WordData"][];
        };
        TranslationContent: {
            /** @description lang_id */
            li?: number;
            /** @description lang_code */
            lc?: string;
            /**
             * @description direction
             * @enum {string}
             */
            d?: "ltr" | "rtl";
            /** @description text */
            tx?: string;
            /** @description subtitle */
            s?: string | null;
            /** @description footer */
            f?: string | null;
            /** @description Highlighted snippet with <b>…</b> tags around matching terms (search only). */
            hl?: string | null;
        };
        WordData: {
            /** @description word_index */
            wi?: number;
            /** @description global_index */
            gi?: number;
            /** @description word text keyed by language code */
            tx?: {
                [key: string]: string;
            } | null;
            /** @description Highlighted word text keyed by language code, with <b>…</b> tags (word search only). */
            hl?: {
                [key: string]: string;
            } | null;
            /** @description root */
            r?: string | null;
            /** @description meaning */
            m?: string | null;
            /** @description metadata */
            meta?: Record<string, never> | null;
        };
        Language: {
            id?: number;
            code?: string;
            name?: string;
            /** @enum {string} */
            direction?: "ltr" | "rtl";
        };
        ChapterMetadata: components["schemas"]["Chapter"][];
        Chapter: {
            chapter_number?: number;
            verse_count?: number;
            revelation_order?: number;
            title?: string;
        };
        AppendixMetadata: components["schemas"]["Appendix"][];
        Appendix: {
            code?: number;
            title?: string;
            snippet?: string;
        };
        BibleResponse: {
            info?: components["schemas"]["BibleResponseInfo"];
            books?: components["schemas"]["BibleBookData"][];
        };
        /** @description Metadata envelope. Reader fields (book, chapter_start/end, verse_start/end) are populated by /bible; search fields (q, total, limit, offset) are populated by /bible/search. */
        BibleResponseInfo: {
            /** @description Number of matching verses in this response page. */
            result_count?: number;
            /** @description Requested book number (reader only). */
            book?: number;
            chapter_start?: number;
            chapter_end?: number;
            verse_start?: number;
            verse_end?: number;
            /** @description The search query as submitted (search only). */
            q?: string;
            /** @description Total matching results across all pages (search only). */
            total?: number;
            limit?: number;
            offset?: number;
        };
        /** @description Summary metadata for one Bible book. */
        BibleBook: {
            /** @description book_number */
            bn?: number;
            /** @description book_name */
            bk?: string;
            /** @description testament (OT or NT) */
            t?: string;
            /** @description chapter_count */
            cc?: number;
            /** @description verse_count */
            vc?: number;
        };
        /** @description A Bible book with nested chapters, returned by /bible and /bible/search. */
        BibleBookData: {
            /** @description book_number */
            bn?: number;
            /** @description book_name */
            bk?: string;
            /** @description testament (OT or NT) */
            t?: string;
            chapters?: components["schemas"]["BibleChapterData"][];
        };
        BibleChapterData: {
            /** @description chapter_number (within the book) */
            cn?: number;
            /** @description Number of matching verses in this chapter (search only). */
            hits?: number;
            verses?: components["schemas"]["BibleVerseData"][];
        };
        BibleVerseData: {
            /** @description verse_number */
            vn?: number;
            /**
             * @description verse_key — book_number:chapter_number:verse_number
             * @example 1:1:1
             */
            vk?: string;
            /**
             * Format: float
             * @description Relevance score (search only).
             */
            sc?: number;
            /** @description translations keyed by language code */
            tr?: {
                [key: string]: components["schemas"]["BibleTranslationContent"];
            };
        };
        BibleTranslationContent: {
            /** @description lang_id */
            li?: number;
            /** @description lang_code */
            lc?: string;
            /**
             * @description direction
             * @enum {string}
             */
            d?: "ltr" | "rtl";
            /** @description text */
            tx?: string;
            /** @description footer/footnote */
            f?: string | null;
            /** @description theological footnotes */
            fn?: string[] | null;
            /** @description highlight with <b> tags (search only) */
            hl?: string | null;
        };
    };
    responses: {
        /** @description The request could not be completed due to a conflict with the current state of the resource. Resolve the conflict and try again. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    message: string;
                };
            };
        };
        /** @description The server cannot find the requested resource. The endpoint may be invalid or the resource may no longer exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    message: string;
                };
            };
        };
        /** @description The server could not understand the request due to invalid syntax. The client should modify the request and try again. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    message: string;
                };
            };
        };
        /** @description The server encountered an unexpected condition that prevented it from fulfilling the request. Report the issue to the support team if it persists. */
        InternalServerErrror: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    message: string;
                };
            };
        };
        /** @description The requested operation is not yet implemented. */
        NotImplementedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example This endpoint is under development. */
                    message: string;
                    /** @example NOT_IMPLEMENTED */
                    code: string;
                };
            };
        };
    };
    parameters: {
        /** @description Language codes for word-level text (subset of langs, e.g. only "ar"). */
        WordLangsParam: string[];
        /** @description Include word-by-word breakdown for each verse. */
        IncludeWordsParam: boolean;
        /** @description Include Arabic root for each word (requires include_words). */
        IncludeRootParam: boolean;
        /** @description Include word meaning for each word (requires include_words). */
        IncludeMeaningParam: boolean;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLanguages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Language"][];
                };
            };
            500: components["responses"]["InternalServerErrror"];
        };
    };
    getChapters: {
        parameters: {
            query?: {
                lang?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterMetadata"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerErrror"];
            501: components["responses"]["NotImplementedError"];
        };
    };
    getAppendices: {
        parameters: {
            query?: {
                lang?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppendixMetadata"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerErrror"];
            501: components["responses"]["NotImplementedError"];
        };
    };
    getQuran: {
        parameters: {
            query: {
                chapter_number_start?: number;
                chapter_number_end?: number;
                verse_start?: number;
                verse_end?: number;
                /** @description Compact verse references. Single verse (1:1), range within a chapter (1:1-3), or comma-separated list (1:2,1:4-5,4:2). When present, takes priority over chapter_number_start/verse_start/verse_end. Max 300 verses. */
                verses?: string;
                /** @description Language codes to include (e.g. en, ar, fr). */
                langs: string[];
                /** @description Language codes for word-level text (subset of langs, e.g. only "ar"). */
                word_langs?: components["parameters"]["WordLangsParam"];
                /** @description Include word-by-word breakdown for each verse. */
                include_words?: components["parameters"]["IncludeWordsParam"];
                /** @description Include Arabic root for each word (requires include_words). */
                include_root?: components["parameters"]["IncludeRootParam"];
                /** @description Include word meaning for each word (requires include_words). */
                include_meaning?: components["parameters"]["IncludeMeaningParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuranResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerErrror"];
            501: components["responses"]["NotImplementedError"];
        };
    };
    search: {
        parameters: {
            query?: {
                /** @description Search query (2–200 characters). Supports quoted phrases and exclusions. Optional when `root` is provided with scope=words. */
                q?: string;
                /** @description Arabic root string (e.g. رحم). When provided with scope=words, performs an exact match on word_root instead of full-text search. Takes priority over q. */
                root?: string;
                /** @description Language codes to search in. Omit for all languages. */
                langs?: string[];
                /** @description Whether to search verse translations or word-level text. */
                scope?: "verses" | "words";
                limit?: number;
                offset?: number;
                /** @description Language codes for word-level text (subset of langs, e.g. only "ar"). */
                word_langs?: components["parameters"]["WordLangsParam"];
                /** @description Include word-by-word breakdown for each verse. */
                include_words?: components["parameters"]["IncludeWordsParam"];
                /** @description Include Arabic root for each word (requires include_words). */
                include_root?: components["parameters"]["IncludeRootParam"];
                /** @description Include word meaning for each word (requires include_words). */
                include_meaning?: components["parameters"]["IncludeMeaningParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuranResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerErrror"];
            501: components["responses"]["NotImplementedError"];
        };
    };
    getBibleBooks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BibleBook"][];
                };
            };
            500: components["responses"]["InternalServerErrror"];
        };
    };
    getBible: {
        parameters: {
            query: {
                /** @description Book number (1 = Genesis, 40 = Matthew, …, 66 = Revelation). */
                book: number;
                /** @description First chapter to include (1-based, within the book). */
                chapter_start: number;
                /** @description Last chapter to include. Defaults to chapter_start. */
                chapter_end?: number;
                /** @description First verse to include. Defaults to 1. */
                verse_start?: number;
                /** @description Last verse to include. Defaults to end of chapter. */
                verse_end?: number;
                /** @description Language codes to include (e.g. en). */
                langs: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BibleResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    searchBible: {
        parameters: {
            query: {
                /** @description Search query (2–200 characters). */
                q: string;
                /** @description Language codes to search in. Omit for all languages. */
                langs?: string[];
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BibleResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
}
