/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List supported languages
         * @description Returns all languages supported by the API, including code, name, and text direction.
         */
        get: operations["getLanguages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * fetches chapter Metadata
         * @description Fetches list of quranic chapter titles, with Metadata and multilingual support
         */
        get: operations["getChapters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appendices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * fetches appendix Metadata
         * @description Fetches list of appendices, with Metadata and multilingual support
         */
        get: operations["getAppendices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quran": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch a range of verses
         * @description Returns a range of verses. Supports multiple languages simultaneously and optional word-by-word or root data.
         */
        get: operations["getQuran"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full-text search across the Quran
         * @description Full-text search across verse content and chapter titles in all indexed languages. Supports fuzzy/partial matching via pg_trgm. Scope can be narrowed to verse translations or word-level text.
         */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/editor/drafts/verse-text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all verse drafts
         * @description Retrieve a list of drafts filtered by status.
         */
        get: operations["listVerseDrafts"];
        put?: never;
        /**
         * Create a new translation draft
         * @description Initial creation of a draft for a specific verse and language.
         */
        post: operations["createVerseDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/editor/drafts/verse-text/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the draft */
                id: number;
            };
            cookie?: never;
        };
        /**
         * Get a specific draft
         * @description Retrieve the full details of a single draft by its ID.
         */
        get: operations["getVerseDraft"];
        put?: never;
        post?: never;
        /**
         * Discard a draft
         * @description Permanent removal of a draft.
         */
        delete: operations["deleteVerseDraft"];
        options?: never;
        head?: never;
        /**
         * Update a draft
         * @description Iteratively update draft content.
         */
        patch: operations["updateVerseDraft"];
        trace?: never;
    };
    "/editor/publish/verse-text/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish a draft
         * @description Archives current live text and promotes draft to live status.
         */
        post: operations["publishVerseText"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/editor/history/verse-text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * View audit logs
         * @description Chronological list of previous versions for a specific verse.
         */
        get: operations["getVerseHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        QuranResponse: {
            info?: components["schemas"]["QuranResponseInfo"];
            chapters?: components["schemas"]["ChapterData"][];
        };
        /** @description Metadata envelope. Reader fields (chapter_start/end, verse_start/end) are populated by /quran; search fields (q, total, limit, offset, scope) are populated by /search. */
        QuranResponseInfo: {
            /** @description Number of matching verses in this response page. */
            result_count?: number;
            chapter_start?: number;
            chapter_end?: number;
            verse_start?: number;
            verse_end?: number;
            /** @description The search query as submitted. */
            q?: string;
            /** @description Total matching results across all pages. */
            total?: number;
            limit?: number;
            offset?: number;
            /** @description Search scope used (verses or words). */
            scope?: string;
        };
        ChapterData: {
            /** @description chapter_number */
            cn?: number;
            titles?: {
                [key: string]: string;
            };
            verses?: components["schemas"]["VerseData"][];
            /** @description Number of matching verses in this chapter (search only). */
            hits?: number;
            /** @description title_match — true when the chapter title matched the query (search only). */
            tm?: boolean;
        };
        VerseData: {
            /** @description verse_index */
            vi?: number;
            /**
             * @description verse_key
             * @example 1:1
             */
            vk?: string;
            /**
             * Format: float
             * @description Relevance score (search only).
             */
            sc?: number;
            /** @description translations keyed by language code */
            tr?: {
                [key: string]: components["schemas"]["TranslationContent"];
            };
            /** @description words */
            w?: components["schemas"]["WordData"][];
        };
        TranslationContent: {
            /** @description lang_id */
            li?: number;
            /** @description lang_code */
            lc?: string;
            /**
             * @description direction
             * @enum {string}
             */
            d?: "ltr" | "rtl";
            /** @description text */
            tx?: string;
            /** @description subtitle */
            s?: string | null;
            /** @description footer */
            f?: string | null;
            /** @description Highlighted snippet with <b>…</b> tags around matching terms (search only). */
            hl?: string | null;
        };
        WordData: {
            /** @description word_index */
            wi?: number;
            /** @description global_index */
            gi?: number;
            /** @description word text keyed by language code */
            tx?: {
                [key: string]: string;
            } | null;
            /** @description Highlighted word text keyed by language code, with <b>…</b> tags (word search only). */
            hl?: {
                [key: string]: string;
            } | null;
            /** @description root */
            r?: string | null;
            /** @description meaning */
            m?: string | null;
            /** @description metadata */
            meta?: Record<string, never> | null;
        };
        /** @enum {string} */
        TranslationStatus: "draft" | "published" | "archived";
        VerseTextHistory: {
            id?: number;
            /**
             * Format: date-time
             * @description archived_at
             */
            at?: string;
            /** @description text/content */
            tx?: string;
        };
        VerseTextDraft: {
            /** @description verse_id */
            vi?: number;
            /** @description lang_id */
            li?: number;
            /** @description text/content */
            tx?: string;
        };
        Language: {
            id?: number;
            code?: string;
            name?: string;
            /** @enum {string} */
            direction?: "ltr" | "rtl";
        };
        ChapterMetadata: components["schemas"]["Chapter"][];
        Chapter: {
            chapter_number?: number;
            verse_count?: number;
            revelation_order?: number;
            title?: string;
        };
        AppendixMetadata: components["schemas"]["Appendix"][];
        Appendix: {
            code?: number;
            title?: string;
            snippet?: string;
        };
    };
    responses: {
        /** @description The request could not be completed due to a conflict with the current state of the resource. Resolve the conflict and try again. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    message: string;
                };
            };
        };
        /** @description The server cannot find the requested resource. The endpoint may be invalid or the resource may no longer exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    message: string;
                };
            };
        };
        /** @description The server could not understand the request due to invalid syntax. The client should modify the request and try again. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    message: string;
                };
            };
        };
        /** @description The server encountered an unexpected condition that prevented it from fulfilling the request. Report the issue to the support team if it persists. */
        InternalServerErrror: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    message: string;
                };
            };
        };
        /** @description The requested operation is not yet implemented. */
        NotImplementedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example This endpoint is under development. */
                    message: string;
                    /** @example NOT_IMPLEMENTED */
                    code: string;
                };
            };
        };
    };
    parameters: {
        /** @description Language codes for word-level text (subset of langs, e.g. only "ar"). */
        WordLangsParam: string[];
        /** @description Include word-by-word breakdown for each verse. */
        IncludeWordsParam: boolean;
        /** @description Include Arabic root for each word (requires include_words). */
        IncludeRootParam: boolean;
        /** @description Include word meaning for each word (requires include_words). */
        IncludeMeaningParam: boolean;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLanguages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Language"][];
                };
            };
            500: components["responses"]["InternalServerErrror"];
        };
    };
    getChapters: {
        parameters: {
            query?: {
                lang?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterMetadata"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerErrror"];
            501: components["responses"]["NotImplementedError"];
        };
    };
    getAppendices: {
        parameters: {
            query?: {
                lang?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppendixMetadata"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerErrror"];
            501: components["responses"]["NotImplementedError"];
        };
    };
    getQuran: {
        parameters: {
            query: {
                chapter_number_start?: number;
                chapter_number_end?: number;
                verse_start?: number;
                verse_end?: number;
                /** @description Compact verse references. Single verse (1:1), range within a chapter (1:1-3), or comma-separated list (1:2,1:4-5,4:2). When present, takes priority over chapter_number_start/verse_start/verse_end. Max 300 verses. */
                verses?: string;
                /** @description Language codes to include (e.g. en, ar, fr). */
                langs: string[];
                /** @description Language codes for word-level text (subset of langs, e.g. only "ar"). */
                word_langs?: components["parameters"]["WordLangsParam"];
                /** @description Include word-by-word breakdown for each verse. */
                include_words?: components["parameters"]["IncludeWordsParam"];
                /** @description Include Arabic root for each word (requires include_words). */
                include_root?: components["parameters"]["IncludeRootParam"];
                /** @description Include word meaning for each word (requires include_words). */
                include_meaning?: components["parameters"]["IncludeMeaningParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuranResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerErrror"];
            501: components["responses"]["NotImplementedError"];
        };
    };
    search: {
        parameters: {
            query?: {
                /** @description Search query (2–200 characters). Supports quoted phrases and exclusions. Optional when `root` is provided with scope=words. */
                q?: string;
                /** @description Arabic root string (e.g. رحم). When provided with scope=words, performs an exact match on word_root instead of full-text search. Takes priority over q. */
                root?: string;
                /** @description Language codes to search in. Omit for all languages. */
                langs?: string[];
                /** @description Whether to search verse translations or word-level text. */
                scope?: "verses" | "words";
                limit?: number;
                offset?: number;
                /** @description Language codes for word-level text (subset of langs, e.g. only "ar"). */
                word_langs?: components["parameters"]["WordLangsParam"];
                /** @description Include word-by-word breakdown for each verse. */
                include_words?: components["parameters"]["IncludeWordsParam"];
                /** @description Include Arabic root for each word (requires include_words). */
                include_root?: components["parameters"]["IncludeRootParam"];
                /** @description Include word meaning for each word (requires include_words). */
                include_meaning?: components["parameters"]["IncludeMeaningParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuranResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerErrror"];
            501: components["responses"]["NotImplementedError"];
        };
    };
    listVerseDrafts: {
        parameters: {
            query?: {
                status?: components["schemas"]["TranslationStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerErrror"];
            501: components["responses"]["NotImplementedError"];
        };
    };
    createVerseDraft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerseTextDraft"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerErrror"];
            501: components["responses"]["NotImplementedError"];
        };
    };
    getVerseDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the draft */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerErrror"];
            501: components["responses"]["NotImplementedError"];
        };
    };
    deleteVerseDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the draft */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerErrror"];
            501: components["responses"]["NotImplementedError"];
        };
    };
    updateVerseDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the draft */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerErrror"];
            501: components["responses"]["NotImplementedError"];
        };
    };
    publishVerseText: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully published. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerErrror"];
            501: components["responses"]["NotImplementedError"];
        };
    };
    getVerseHistory: {
        parameters: {
            query: {
                verse_id: number;
                lang_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerseTextHistory"][];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerErrror"];
            501: components["responses"]["NotImplementedError"];
        };
    };
}
